# Default values.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

name: technical-on-boarding
image: quay.io/samsung_cnct/technical-on-boarding-container:prod
host: technical-on-boarding.cnct.io
ingress: true
onboard:
  org: samsung-cnct
  repo: technical-on-boarding #home for new issues created
  clientId: REPLACE
  clientSecret: REPLACE
